PLAYERS = {
    "Hardik Pandya":       {"role":"ALL-ROUNDER",  "country":"India",        "base":350,"pts":47},
    "Virat Kohli":         {"role":"BATSMAN",       "country":"India",        "base":450,"pts":47},
    "Rohit Sharma":        {"role":"BATSMAN",       "country":"India",        "base":450,"pts":47},
    "Jasprit Bumrah":      {"role":"BOWLER",        "country":"India",        "base":400,"pts":47},
    "Suryakumar Yadav":    {"role":"BATSMAN",       "country":"India",        "base":350,"pts":47},
    "MS Dhoni":            {"role":"WICKETKEEPER",  "country":"India",        "base":450,"pts":46},
    "Ab de Villers":       {"role":"WICKETKEEPER",  "country":"South Africa", "base":250,"pts":46},
    "Trent Boult":         {"role":"BOWLER",        "country":"New Zealand",  "base":200,"pts":46},
    "Lasith Malinga":      {"role":"BOWLER",        "country":"Sri Lanka",    "base":300,"pts":46},
    "Keiron Pollard":      {"role":"ALL-ROUNDER",   "country":"West Indies",  "base":200,"pts":46},
    "DJ Bravo":            {"role":"ALL-ROUNDER",   "country":"West Indies",  "base":200,"pts":46},
    "Shane Watson":        {"role":"ALL-ROUNDER",   "country":"Australia",    "base":250,"pts":46},
    "Shreyas Iyer":        {"role":"BATSMAN",       "country":"India",        "base":200,"pts":45},
    "Pat Cummins":         {"role":"ALL-ROUNDER",   "country":"Australia",    "base":200,"pts":45},
    "Josh Hazlewood":      {"role":"BOWLER",        "country":"Australia",    "base":200,"pts":45},
    "Axar Patel":          {"role":"ALL-ROUNDER",   "country":"India",        "base":200,"pts":45},
    "Marcus Stoinis":      {"role":"ALL-ROUNDER",   "country":"Australia",    "base":250,"pts":45},
    "Ben Stokes":          {"role":"ALL-ROUNDER",   "country":"England",      "base":300,"pts":45},
    "Varun Chakravarthy":  {"role":"BOWLER",        "country":"India",        "base":300,"pts":45},
    "Tilak Varma":         {"role":"BATSMAN",       "country":"India",        "base":300,"pts":45},
    "Rishabh Pant":        {"role":"WICKETKEEPER",  "country":"India",        "base":350,"pts":44},
    "KL Rahul":            {"role":"WICKETKEEPER",  "country":"India",        "base":350,"pts":44},
    "Ishan Kishan":        {"role":"WICKETKEEPER",  "country":"India",        "base":250,"pts":44},
    "Nicholas Pooran":     {"role":"WICKETKEEPER",  "country":"West Indies",  "base":250,"pts":44},
    "Rashid Khan":         {"role":"ALL-ROUNDER",   "country":"Afghanistan",  "base":300,"pts":44},
    "Shubman Gill":        {"role":"BATSMAN",       "country":"India",        "base":300,"pts":44},
    "Yashasvi Jaiswal":    {"role":"BATSMAN",       "country":"India",        "base":300,"pts":44},
    "Ruturaj Gaikwad":     {"role":"BATSMAN",       "country":"India",        "base":300,"pts":44},
    "Mohammad Shami":      {"role":"BOWLER",        "country":"India",        "base":250,"pts":44},
    "Mohammed Siraj":      {"role":"BOWLER",        "country":"India",        "base":200,"pts":44},
    "Abhishek Sharma":     {"role":"BATSMAN",       "country":"India",        "base":300,"pts":43},
    "Ravichandran Ashwin": {"role":"ALL-ROUNDER",   "country":"India",        "base":250,"pts":42},
    "Rajat Patidar":       {"role":"BATSMAN",       "country":"India",        "base":250,"pts":42},
    "Steve Smith":         {"role":"BATSMAN",       "country":"Australia",    "base":300,"pts":42},
    "Kagiso Rabada":       {"role":"BOWLER",        "country":"South Africa", "base":250,"pts":42},
    "Sunil Narine":        {"role":"ALL-ROUNDER",   "country":"West Indies",  "base":200,"pts":42},
    "Jos Buttler":         {"role":"WICKETKEEPER",  "country":"England",      "base":200,"pts":42},
    "Heinrich Klaasen":    {"role":"WICKETKEEPER",  "country":"South Africa", "base":200,"pts":42},
    "Glenn Phillips":      {"role":"WICKETKEEPER",  "country":"New Zealand",  "base":250,"pts":42},
    "Arshdeep Singh":      {"role":"BOWLER",        "country":"India",        "base":250,"pts":42},
    "Marco Jansen":        {"role":"ALL-ROUNDER",   "country":"South Africa", "base":200,"pts":42},
    "Tristan Stubbs":      {"role":"BATSMAN",       "country":"South Africa", "base":250,"pts":42},
    "Tim Southee":         {"role":"BOWLER",        "country":"New Zealand",  "base":200,"pts":40},
    "Lockie Ferguson":     {"role":"ALL-ROUNDER",   "country":"New Zealand",  "base":200,"pts":40},
    "Jason Holder":        {"role":"ALL-ROUNDER",   "country":"West Indies",  "base":300,"pts":40},
    "David Warner":        {"role":"BATSMAN",       "country":"Australia",    "base":200,"pts":40},
    "Cameron Green":       {"role":"ALL-ROUNDER",   "country":"Australia",    "base":200,"pts":40},
    "Tim David":           {"role":"ALL-ROUNDER",   "country":"Australia",    "base":200,"pts":40},
    "David Miller":        {"role":"BATSMAN",       "country":"South Africa", "base":250,"pts":40},
    "Shimron Hetmyer":     {"role":"BATSMAN",       "country":"West Indies",  "base":200,"pts":40},
    "Faf Du Plessis":      {"role":"BATSMAN",       "country":"South Africa", "base":250,"pts":40},
    "Sanju Samson":        {"role":"WICKETKEEPER",  "country":"India",        "base":300,"pts":40},
    "Deepak Chahar":       {"role":"BOWLER",        "country":"India",        "base":150,"pts":40},
    "Nitish Reddy":        {"role":"ALL-ROUNDER",   "country":"India",        "base":100,"pts":40},
    "Jofra Archer":        {"role":"BOWLER",        "country":"England",      "base":250,"pts":40},
    "Kuldeep Yadav":       {"role":"BOWLER",        "country":"India",        "base":250,"pts":40},
    "Washington Sundar":   {"role":"ALL-ROUNDER",   "country":"India",        "base":250,"pts":40},
    "Rinku Singh":         {"role":"BATSMAN",       "country":"India",        "base":300,"pts":41},
    "Sai Sudharsan":       {"role":"BATSMAN",       "country":"India",        "base":200,"pts":39},
    "Riyan Parag":         {"role":"ALL-ROUNDER",   "country":"India",        "base":150,"pts":39},
    "Harshal Patel":       {"role":"BOWLER",        "country":"India",        "base":250,"pts":39},
    "Shivam Dube":         {"role":"ALL-ROUNDER",   "country":"India",        "base":250,"pts":40},
    "Kane Williamson":     {"role":"BATSMAN",       "country":"New Zealand",  "base":100,"pts":40},
    "Yuzvendra Chahal":    {"role":"BOWLER",        "country":"India",        "base":250,"pts":38},
    "Wanindu Hasaranga":   {"role":"ALL-ROUNDER",   "country":"Sri Lanka",    "base":200,"pts":38},
    "Liam Livingstone":    {"role":"ALL-ROUNDER",   "country":"England",      "base":200,"pts":38},
    "Glenn Maxwell":       {"role":"ALL-ROUNDER",   "country":"Australia",    "base":250,"pts":38},
    "Andre Russell":       {"role":"ALL-ROUNDER",   "country":"West Indies",  "base":250,"pts":38},
    "Mitchell Starc":      {"role":"BOWLER",        "country":"Australia",    "base":200,"pts":43},
    "Venkatesh Iyer":      {"role":"ALL-ROUNDER",   "country":"India",        "base":200,"pts":38},
    "Krunal Pandya":       {"role":"ALL-ROUNDER",   "country":"India",        "base":200,"pts":38},
    "Noor Ahmad":          {"role":"BOWLER",        "country":"Afghanistan",  "base":200,"pts":38},
    "Bhuvneshwar Kumar":   {"role":"BOWLER",        "country":"India",        "base":200,"pts":38},
    "Shardul Thakur":      {"role":"BOWLER",        "country":"India",        "base":200,"pts":36},
    "Umran Malik":         {"role":"BOWLER",        "country":"India",        "base":200,"pts":38},
    "Phil Salt":           {"role":"BATSMAN",       "country":"England",      "base":200,"pts":38},
    "Harry Brook":         {"role":"BATSMAN",       "country":"England",      "base":150,"pts":38},
    "Travis Head":         {"role":"BATSMAN",       "country":"Australia",    "base":200,"pts":42},
    "Daryl Mitchell":      {"role":"BATSMAN",       "country":"New Zealand",  "base":200,"pts":42},
    "Mark Wood":           {"role":"BOWLER",        "country":"England",      "base":200,"pts":38},
    "Anrich Nortje":       {"role":"BOWLER",        "country":"South Africa", "base":200,"pts":37},
    "Romario Shepherd":    {"role":"ALL-ROUNDER",   "country":"West Indies",  "base":150,"pts":38},
    "Maheesh Theekshana":  {"role":"BOWLER",        "country":"Sri Lanka",    "base":200,"pts":36},
    "Matheesha Pathirana": {"role":"BOWLER",        "country":"Sri Lanka",    "base":100,"pts":38},
    "Mitchell Marsh":      {"role":"BATSMAN",       "country":"Australia",    "base":200,"pts":38},
    "Alzarri Joseph":      {"role":"BOWLER",        "country":"West Indies",  "base":100,"pts":38},
    "Gerald Coetzee":      {"role":"BOWLER",        "country":"South Africa", "base":200,"pts":34},
    "Devon Conway":        {"role":"WICKETKEEPER",  "country":"New Zealand",  "base":250,"pts":40},
    "Quinton De Kock":     {"role":"WICKETKEEPER",  "country":"South Africa", "base":200,"pts":38},
    "Jitesh Sharma":       {"role":"WICKETKEEPER",  "country":"India",        "base":250,"pts":37},
    "Dhruv Jurel":         {"role":"WICKETKEEPER",  "country":"India",        "base":250,"pts":36},
    "Prabhsimran Singh":   {"role":"WICKETKEEPER",  "country":"India",        "base":100,"pts":36},
    "Devdutt Padikkal":    {"role":"BATSMAN",       "country":"India",        "base":150,"pts":36},
    "Nitish Rana":         {"role":"BATSMAN",       "country":"India",        "base":100,"pts":38},
    "Ajinkya Rahane":      {"role":"BATSMAN",       "country":"India",        "base":150,"pts":38},
    "Rahul Tripathi":      {"role":"BATSMAN",       "country":"India",        "base":100,"pts":33},
    "Deepak Hooda":        {"role":"BATSMAN",       "country":"India",        "base":100,"pts":34},
    "Mayank Yadav":        {"role":"BOWLER",        "country":"India",        "base":150,"pts":37},
    "Harshit Rana":        {"role":"BOWLER",        "country":"India",        "base":150,"pts":36},
    "Mukesh Kumar":        {"role":"BOWLER",        "country":"India",        "base":150,"pts":34},
    "Sandeep Sharma":      {"role":"BOWLER",        "country":"India",        "base":150,"pts":38},
    "Ravi Bishnoi":        {"role":"BOWLER",        "country":"India",        "base":150,"pts":33},
    "Rahul Chahar":        {"role":"BOWLER",        "country":"India",        "base":100,"pts":38},
    "Yash Dayal":          {"role":"BOWLER",        "country":"India",        "base":100,"pts":36},
    "Avesh Khan":          {"role":"BOWLER",        "country":"India",        "base":100,"pts":33},
    "Khaleel Ahmed":       {"role":"BOWLER",        "country":"India",        "base":100,"pts":32},
    "T. Natarajan":        {"role":"BOWLER",        "country":"India",        "base":150,"pts":35},
    "Umesh Yadav":         {"role":"BOWLER",        "country":"India",        "base":100,"pts":36},
    "Shahrukh Khan":       {"role":"BATSMAN",       "country":"India",        "base":100,"pts":33},
    "Manish Pandey":       {"role":"BATSMAN",       "country":"India",        "base":100,"pts":36},
    "Chris Gayle":         {"role":"ALL-ROUNDER",   "country":"West Indies",  "base":250,"pts":45},
    "Yuvraj Singh":        {"role":"ALL-ROUNDER",   "country":"India",        "base":250,"pts":45},
    "Suresh Raina":        {"role":"ALL-ROUNDER",   "country":"India",        "base":200,"pts":46},
    "Mohammad Nabi":       {"role":"ALL-ROUNDER",   "country":"Afghanistan",  "base":100,"pts":42},
    "Sam Curran":          {"role":"ALL-ROUNDER",   "country":"England",      "base":150,"pts":36},
    "Chris Morris":        {"role":"ALL-ROUNDER",   "country":"South Africa", "base":100,"pts":43},
    "Ben Cutting":         {"role":"ALL-ROUNDER",   "country":"Australia",    "base":350,"pts":40},
    "Dale Steyn":          {"role":"BOWLER",        "country":"South Africa", "base":300,"pts":45},
}
